#ifndef CHIPCOUNTER_GLOBAL_H
#define CHIPCOUNTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CHIPCOUNTER_LIB
# define CHIPCOUNTER_EXPORT Q_DECL_EXPORT
#else
# define CHIPCOUNTER_EXPORT Q_DECL_IMPORT
#endif

#endif // CHIPCOUNTER_GLOBAL_H
